### ISSUE TITLE
Not detecting permission groups

### ISSUE THREAD

**Issue by mike-544** [xGoldenK/CustomTabCompleter#2]
Hi, i am unsure on how to get this plugin to use the groups i have set up in Luck Perms.
(Also sorry i am new to github, so i do not really understand the formatting. Setting the code below in a code block seems to make it be formatted incorrectly so i chose to put it as quote instead)

This is how i have it set up atm:

> groups:
>   default:
>     list:
>       - plot
>       - hat
>       - p
>       - spawn
>       - shop
>       - worth
>       - adboard
>       - advert
>       - ad
>       - helpguide
>       - hg
>       - tokenshop
>       - ts
>       - prestige
>       - rankup
>       - levelup
>       - pay
>       - rules
>       - start
>       - fly
>       - craft
>       - ec
>       - enderchest
>       - sell
>       - sellhand
>       - esell
>       - quests
>       - bal
>       - baltop
>       - stats
>       - tpa
>       - tpaccept
>   helper:
>     list:
>       - plot
>       - p
>       - spawn
>       - shop
>       - worth
>       - adboard
>       - advert
>       - ad
>       - helpguide
>       - hg
>       - hat
>       - tokenshop
>       - ts
>       - prestige
>       - rankup
>       - levelup
>       - pay
>       - rules
>       - start
>       - fly
>       - craft
>       - ec
>       - enderchest
>       - sell
>       - sellhand
>       - esell
>       - quests
>       - bal
>       - baltop
>       - stats
>       - tp
>       - kick
>       - tempmute
>       - unmute
>       - warn
>       - warns
>       - gamemode

I was also unsure if i had to repeat each command for each group or if it would use the inheritance found in the group (since helper inherits from default rank)
I do not understand what i am doing wrong as the group is definitely spelt correctly and has the correct capitalisation etc.

**Comment by Quik2007** [comment]
The file groups.yml should look somewhat like this:
```yml
groups:
  default:
    is_list_whitelist: true
    commands:
    - all
    - the
    - commands
    - your
    - users
    - should
    - have
    - access
    - to
  another_group:
    is_list_whitelist: true
    commands:
    - an
    - other
    - group
```

I think that your file isn't properly formatted, it should look somewhat like this:
```yml
groups:
  default:
    is_list_whitelist: true
    list:
    - plot
    - hat
    - p
    - spawn
    - shop
    - worth
    - adboard
    - advert
    - ad
    - helpguide
    - hg
    - tokenshop
    - ts
    - prestige
    - rankup
    - levelup
    - pay
    - rules
    - start
    - fly
    - craft
    - ec
    - enderchest
    - sell
    - sellhand
    - esell
    - quests
    - bal
    - baltop
    - stats
    - tpa
    - tpaccept
    helper:
    list:
    - plot
    - p
    - spawn
    - shop
    - worth
    - adboard
    - advert
    - ad
    - helpguide
    - hg
    - hat
    - tokenshop
    - ts
    - prestige
    - rankup
    - levelup
    - pay
    - rules
    - start
    - fly
    - craft
    - ec
    - enderchest
    - sell
    - sellhand
    - esell
    - quests
    - bal
    - baltop
    - stats
    - tp
    - kick
    - tempmute
    - unmute
    - warn
    - warns
    - gamemode
```

But I'm also not quite sure because I encounter issues with the `is_list_whitelist` option (doesn't work for me at all).
